### ISSUE TITLE
error with Logger

### ISSUE THREAD

**Issue by sudomoose** [Moosecoop/PrettyLog#3]
running `npm test` gives this error: [image](https://i.imgur.com/nRp207A.png)

```
prettyLog('Status set', false, false);
^

TypeError: Class constructor Logger cannot be invoked without 'new'
    at Object.<anonymous> (C:\Users\User\Documents\PrettyLog\test.js:8:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
npm ERR! Test failed.  See above for more details.
```

**Comment by sudomoose** [comment]
@MrSakamoto-san

**Comment by ghost** [comment]
did you even change tests and etc to work with new code
